import { RouteInfo } from './vertical-sidebar.metadata';

export const ROUTES: RouteInfo[] = [
  // Dashboard
  // {
  //   path: '',
  //   title: 'Dashboard',
  //   icon: 'icon-speedometer',
  //   class: 'has-arrow',
  //   label: '',
  //   labelClass: 'side-badge badge badge-pill text-white badge-danger',
  //   extralink: false,
  //   submenu: [
  //     {
  //       path: '/dashboard/dashboard1', //2,3,4
  //       title: 'Minimal',
  //       icon: 'mdi mdi-adjust',
  //       class: '',
  //       label: '',
  //       labelClass: '',
  //       extralink: false,
  //       submenu: [],
  //     },
  //   ],
  // },
  // Organaization
  // {
  //   path: '/organaization',
  //   title: 'Organization',
  //   icon: 'mdi mdi-adjust',
  //   class: '',
  //   label: '',
  //   labelClass: 'side-badge badge badge-pill text-white badge-danger',
  //   extralink: false,
  //   submenu: [],
  // },
  {
    path: '/allow_permission',
    title: 'Allow Permission',
    icon: 'mdi mdi-adjust',
    class: '',
    label: '',
    labelClass: 'side-badge badge badge-pill text-white badge-danger',
    extralink: false,
    submenu: [],
  },
  {
    path: '/allow_purpose',
    title: 'Allow Purpose',
    icon: 'mdi mdi-adjust',
    class: '',
    label: '',
    labelClass: 'side-badge badge badge-pill text-white badge-danger',
    extralink: false,
    submenu: [],
  },
  // Operating Unit Customization
  {
    path: '/operating_unit',
    title: 'Operating Unit',
    icon: 'mdi mdi-adjust',
    class: '',
    label: '',
    labelClass: 'side-badge badge badge-pill text-white badge-danger',
    extralink: false,
    submenu: [],
  },
  {
    path: '/bank',
    title: 'Bank',
    icon: 'mdi mdi-adjust',
    class: '',
    label: '',
    labelClass: 'side-badge badge badge-pill text-white badge-danger',
    extralink: false,
    submenu: [],
  },
  // User
  {
    path: '/user',
    title: 'User',
    icon: 'mdi mdi-adjust',
    class: '',
    label: '',
    labelClass: 'side-badge badge badge-pill text-white badge-danger',
    extralink: false,
    submenu: [],
  },
  {
    path: '/generate_batch',
    title: 'Generate Batch',
    icon: 'mdi mdi-adjust',
    class: '',
    label: '',
    labelClass: 'side-badge badge badge-pill text-white badge-danger',
    extralink: false,
    submenu: [],
  },
  {
    path: '/verification',
    title: 'Verification',
    icon: 'mdi mdi-adjust',
    class: '',
    label: '',
    labelClass: 'side-badge badge badge-pill text-white badge-danger',
    extralink: false,
    submenu: [],
  },
  {
    path: '/reconciliation',
    title: 'Direct Deposit Reconciliation',
    icon: 'mdi mdi-adjust',
    class: '',
    label: '',
    labelClass: 'side-badge badge badge-pill text-white badge-danger',
    extralink: false,
    submenu: [],
  },
  {
    path: '/mark_ready',
    title: 'Ready For ERP',
    icon: 'mdi mdi-adjust',
    class: '',
    label: '',
    labelClass: 'side-badge badge badge-pill text-white badge-danger',
    extralink: false,
    submenu: [],
  },
  {
    path: '/knock_off',
    title: 'Knock Off',
    icon: 'mdi mdi-adjust',
    class: '',
    label: '',
    labelClass: 'side-badge badge badge-pill text-white badge-danger',
    extralink: false,
    submenu: [],
  },
  // {
  //   path: '/bd_reconcil',
  //   title: 'Bank Deposit Reconciliation',
  //   icon: 'mdi mdi-adjust',
  //   class: '',
  //   label: '',
  //   labelClass: 'side-badge badge badge-pill text-white badge-danger',
  //   extralink: false,
  //   submenu: [],
  // },
  {
    path: '/eraseed_collection',
    title: 'Eraseed Collection',
    icon: 'mdi mdi-adjust',
    class: '',
    label: '',
    labelClass: 'side-badge badge badge-pill text-white badge-danger',
    extralink: false,
    submenu: [],
  },
  {
    path: '/assigning-collectors',
    title: 'Assigning Collectors',
    icon: 'mdi mdi-adjust',
    class: '',
    label: '',
    labelClass: 'side-badge badge badge-pill text-white badge-danger',
    extralink: false,
    submenu: [],
  },
  {
    path: '/users-donation',
    title: 'Users Donation',
    icon: 'mdi mdi-adjust',
    class: '',
    label: '',
    labelClass: 'side-badge badge badge-pill text-white badge-danger',
    extralink: false,
    submenu: [],
  },
  {
    path: '/acknowledgement-list',
    title: 'Acknowledgement List',
    icon: 'mdi mdi-adjust',
    class: '',
    label: '',
    labelClass: 'side-badge badge badge-pill text-white badge-danger',
    extralink: false,
    submenu: [],
  },
  // Deposit
  {
    path: '',
    title: 'Deposit',
    icon: 'icon-list',
    class: 'has-arrow',
    label: '',
    labelClass: 'side-badge badge badge-pill text-white badge-danger',
    extralink: false,
    submenu: [
      {
        path: '/deposit/cash_deopsit_bank',
        title: 'Cash deposit bank',
        icon: 'mdi mdi-adjust',
        class: '',
        label: '',
        labelClass: '',
        extralink: false,
        submenu: [],
      },
      {
        path: '/deposit/cheque_deopsit_bank',
        title: 'Cheque deposit bank',
        icon: 'mdi mdi-adjust',
        class: '',
        label: '',
        labelClass: '',
        extralink: false,
        submenu: [],
      },
      {
        path: '/deposit/cheque_clearance',
        title: 'Cheque clearance',
        icon: 'mdi mdi-adjust',
        class: '',
        label: '',
        labelClass: '',
        extralink: false,
        submenu: [],
      },
      {
        path: '/deposit/material_store_placement',
        title: 'Material store',
        icon: 'mdi mdi-adjust',
        class: '',
        label: '',
        labelClass: '',
        extralink: false,
        submenu: [],
      }
    ],
  },
  // Box Management
  {
    path: '',
    title: 'Box Management',
    icon: 'icon-list',
    class: 'has-arrow',
    label: '',
    labelClass: 'side-badge badge badge-pill text-white badge-danger',
    extralink: false,
    submenu: [
      {
        path: '/box_management/vendor',
        title: 'Vendor',
        icon: 'mdi mdi-adjust',
        class: '',
        label: '',
        labelClass: '',
        extralink: false,
        submenu: [],
      },
      {
        path: '/box_management/box_sell',
        title: 'Box Sell',
        icon: 'mdi mdi-adjust',
        class: '',
        label: '',
        labelClass: '',
        extralink: false,
        submenu: [],
      },
      {
        path: '/box_management/box_receive',
        title: 'Box Receive',
        icon: 'mdi mdi-adjust',
        class: '',
        label: '',
        labelClass: '',
        extralink: false,
        submenu: [],
      },
      {
        path: '/box_management/box_stock',
        title: 'Box Stock',
        icon: 'mdi mdi-adjust',
        class: '',
        label: '',
        labelClass: '',
        extralink: false,
        submenu: [],
      },
      {
        path: '/box_management/box_stock_ou',
        title: 'OU Stock',
        icon: 'mdi mdi-adjust',
        class: '',
        label: '',
        labelClass: '',
        extralink: false,
        submenu: [],
      },
      {
        path: '/box_management/box_stock_collector',
        title: 'Collector Stock',
        icon: 'mdi mdi-adjust',
        class: '',
        label: '',
        labelClass: '',
        extralink: false,
        submenu: [],
      }
    ],
  },
  // Donation
  {
    path: '',
    title: 'Donation',
    icon: 'icon-list',
    class: 'has-arrow',
    label: '',
    labelClass: 'side-badge badge badge-pill text-white badge-danger',
    extralink: false,
    submenu: [
      {
        path: '/donation/cell_master',
        title: 'Cell Master',
        icon: 'mdi mdi-adjust',
        class: '',
        label: '',
        labelClass: '',
        extralink: false,
        submenu: [],
      },
      {
        path: '/donation/type',
        title: 'Donation Type',
        icon: 'mdi mdi-adjust',
        class: '',
        label: '',
        labelClass: '',
        extralink: false,
        submenu: [],
      },
      {
        path: '/donation/sub_type',
        title: 'Sub Type',
        icon: 'mdi mdi-adjust',
        class: '',
        label: '',
        labelClass: '',
        extralink: false,
        submenu: [],
      },
      {
        path: '/donation/monthly_target',
        title: 'Monthly Target',
        icon: 'mdi mdi-adjust',
        class: '',
        label: '',
        labelClass: '',
        extralink: false,
        submenu: [],
      },
    ],
  },
  // Donor
  {
    path: '',
    title: 'Donor',
    icon: 'icon-list',
    class: 'has-arrow',
    label: '',
    labelClass: 'side-badge badge badge-pill text-white badge-danger',
    extralink: false,
    submenu: [
      {
        path: '/donor/adv_setup',
        title: 'Advance Setup',
        icon: 'mdi mdi-adjust',
        class: '',
        label: '',
        labelClass: '',
        extralink: false,
        submenu: [],
      },
      {
        path: '/donor/basic',
        title: 'Basic Donor',
        icon: 'mdi mdi-adjust',
        class: '',
        label: '',
        labelClass: '',
        extralink: false,
        submenu: [],
      },
      {
        path: '/donor/type',
        title: 'Donor Type',
        icon: 'mdi mdi-adjust',
        class: '',
        label: '',
        labelClass: '',
        extralink: false,
        submenu: [],
      },
    ],
  },
  // Madani Basta
  {
    path: '',
    title: 'Madani Basta',
    icon: 'icon-list',
    class: 'has-arrow',
    label: '',
    labelClass: 'side-badge badge badge-pill text-white badge-danger',
    extralink: false,
    submenu: [
      {
        path: '/madni_basta/category',
        title: 'Category',
        icon: 'mdi mdi-adjust',
        class: '',
        label: '',
        labelClass: '',
        extralink: false,
        submenu: [],
      },
      {
        path: '/madni_basta/sub_category',
        title: 'Sub Category',
        icon: 'mdi mdi-adjust',
        class: '',
        label: '',
        labelClass: '',
        extralink: false,
        submenu: [],
      },
      {
        path: '/madni_basta/event',
        title: 'Event',
        icon: 'mdi mdi-adjust',
        class: '',
        label: '',
        labelClass: '',
        extralink: false,
        submenu: [],
      },
      {
        path: '/madni_basta/place',
        title: 'Place',
        icon: 'mdi mdi-adjust',
        class: '',
        label: '',
        labelClass: '',
        extralink: false,
        submenu: [],
      },
    ],
  },
  // Transaction
  {
    path: '',
    title: 'Transaction',
    icon: 'icon-list',
    class: 'has-arrow',
    label: '',
    labelClass: 'side-badge badge badge-pill text-white badge-danger',
    extralink: false,
    submenu: [
      {
        path: '/transaction/cash_cheque_list',
        title: 'Cash / Cheque List',
        icon: 'mdi mdi-adjust',
        class: '',
        label: '',
        labelClass: '',
        extralink: false,
        submenu: [],
      },
      {
        path: '/transaction/cash_cheque',
        title: 'Cash / Cheque',
        icon: 'mdi mdi-adjust',
        class: '',
        label: '',
        labelClass: '',
        extralink: false,
        submenu: [],
      },
      {
        path: '/transaction/deposit',
        title: 'Deposit',
        icon: 'mdi mdi-adjust',
        class: '',
        label: '',
        labelClass: '',
        extralink: false,
        submenu: [],
      },
      {
        path: '/transaction/material_list',
        title: 'Material List',
        icon: 'mdi mdi-adjust',
        class: '',
        label: '',
        labelClass: '',
        extralink: false,
        submenu: [],
      },
      {
        path: '/transaction/material',
        title: 'Material',
        icon: 'mdi mdi-adjust',
        class: '',
        label: '',
        labelClass: '',
        extralink: false,
        submenu: [],
      },
      {
        path: '/transaction/bank_direct_deposit',
        title: 'Bank Direct Deposit',
        icon: 'mdi mdi-adjust',
        class: '',
        label: '',
        labelClass: '',
        extralink: false,
        submenu: [],
      },
      {
        path: '/transaction/bank_direct_deposit_upload',
        title: 'Bank Direct Deposit Upload',
        icon: 'mdi mdi-adjust',
        class: '',
        label: '',
        labelClass: '',
        extralink: false,
        submenu: [],
      },
      {
        path: '/transaction/bank_direct_deposit_edit',
        title: 'Bank Direct Deposit Edit',
        icon: 'mdi mdi-adjust',
        class: '',
        label: '',
        labelClass: '',
        extralink: false,
        submenu: [],
      }
    ],
  },
   // Print
   {
    path: '',
    title: 'Print',
    icon: 'icon-list',
    class: 'has-arrow',
    label: '',
    labelClass: 'side-badge badge badge-pill text-white badge-danger',
    extralink: false,
    submenu: [
      {
        path: '/blank/cash_cheque_color',
        title: 'Cash Cheque Color',
        icon: 'mdi mdi-adjust',
        class: '',
        label: '',
        labelClass: '',
        extralink: false,
        submenu: [],
      },
      {
        path: '/blank/cash_cheque_black',
        title: 'Cash Cheque Black',
        icon: 'mdi mdi-adjust',
        class: '',
        label: '',
        labelClass: '',
        extralink: false,
        submenu: [],
      },
      {
        path: '/blank/material_color',
        title: 'Material Color',
        icon: 'mdi mdi-adjust',
        class: '',
        label: '',
        labelClass: '',
        extralink: false,
        submenu: [],
      },
      {
        path: '/blank/material_black',
        title: 'Material Black',
        icon: 'mdi mdi-adjust',
        class: '',
        label: '',
        labelClass: '',
        extralink: false,
        submenu: [],
      },
      {
        path: '/blank/faq',
        title: 'Faq',
        icon: 'mdi mdi-adjust',
        class: '',
        label: '',
        labelClass: '',
        extralink: false,
        submenu: [],
      }
    ],
  },
  // Admin
  // {
  //   path: '',
  //   title: 'Administration',
  //   icon: 'icon-list',
  //   class: 'has-arrow',
  //   label: '',
  //   labelClass: 'side-badge badge badge-pill text-white badge-danger',
  //   extralink: false,
  //   submenu: [
  //     {
  //       path: '/admin/user_list',
  //       title: 'User',
  //       icon: 'mdi mdi-adjust',
  //       class: '',
  //       label: '',
  //       labelClass: '',
  //       extralink: false,
  //       submenu: [],
  //     },
  //   ],
  // }
];
